/**
 * Author
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { InlineResponse2004DataNew } from './inlineResponse2004DataNew';

export class InlineResponse2004Data {
    'id': string;
    'key': string;
    'rev': string;
    '_new': InlineResponse2004DataNew;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "_id",
            "type": "string"
        },
        {
            "name": "key",
            "baseName": "_key",
            "type": "string"
        },
        {
            "name": "rev",
            "baseName": "_rev",
            "type": "string"
        },
        {
            "name": "_new",
            "baseName": "new",
            "type": "InlineResponse2004DataNew"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse2004Data.attributeTypeMap;
    }
}

