/**
 * Author
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class InlineObject2 {
    'actor': string;
    'action': InlineObject2.ActionEnum;
    'resource': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "actor",
            "baseName": "actor",
            "type": "string"
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "InlineObject2.ActionEnum"
        },
        {
            "name": "resource",
            "baseName": "resource",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InlineObject2.attributeTypeMap;
    }
}

export namespace InlineObject2 {
    export enum ActionEnum {
        Read = <any> 'read',
        Delete = <any> 'delete',
        Edit = <any> 'edit'
    }
}
