/* tslint:disable */
/* eslint-disable */
/**
 * Author
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse2004DataNew,
    InlineResponse2004DataNewFromJSON,
    InlineResponse2004DataNewFromJSONTyped,
    InlineResponse2004DataNewToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse2004Data
 */
export interface InlineResponse2004Data {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2004Data
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2004Data
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2004Data
     */
    rev: string;
    /**
     * 
     * @type {InlineResponse2004DataNew}
     * @memberof InlineResponse2004Data
     */
    _new: InlineResponse2004DataNew;
}

export function InlineResponse2004DataFromJSON(json: any): InlineResponse2004Data {
    return InlineResponse2004DataFromJSONTyped(json, false);
}

export function InlineResponse2004DataFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2004Data {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['_id'],
        'key': json['_key'],
        'rev': json['_rev'],
        '_new': InlineResponse2004DataNewFromJSON(json['new']),
    };
}

export function InlineResponse2004DataToJSON(value?: InlineResponse2004Data | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_id': value.id,
        '_key': value.key,
        '_rev': value.rev,
        'new': InlineResponse2004DataNewToJSON(value._new),
    };
}


