/* tslint:disable */
/* eslint-disable */
/**
 * Author
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse2003Data
 */
export interface InlineResponse2003Data {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2003Data
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2003Data
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2003Data
     */
    description: string;
}

export function InlineResponse2003DataFromJSON(json: any): InlineResponse2003Data {
    return InlineResponse2003DataFromJSONTyped(json, false);
}

export function InlineResponse2003DataFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2003Data {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['_id'],
        'name': json['name'],
        'description': json['description'],
    };
}

export function InlineResponse2003DataToJSON(value?: InlineResponse2003Data | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_id': value.id,
        'name': value.name,
        'description': value.description,
    };
}


