/* tslint:disable */
/* eslint-disable */
/**
 * Author
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse2004DataNew
 */
export interface InlineResponse2004DataNew {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2004DataNew
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2004DataNew
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2004DataNew
     */
    from: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2004DataNew
     */
    to: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2004DataNew
     */
    rev: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2004DataNew
     */
    relationship: string;
}

export function InlineResponse2004DataNewFromJSON(json: any): InlineResponse2004DataNew {
    return InlineResponse2004DataNewFromJSONTyped(json, false);
}

export function InlineResponse2004DataNewFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2004DataNew {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': json['_key'],
        'id': json['_id'],
        'from': json['_from'],
        'to': json['_to'],
        'rev': json['_rev'],
        'relationship': json['relationship'],
    };
}

export function InlineResponse2004DataNewToJSON(value?: InlineResponse2004DataNew | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_key': value.key,
        '_id': value.id,
        '_from': value.from,
        '_to': value.to,
        '_rev': value.rev,
        'relationship': value.relationship,
    };
}


