/* tslint:disable */
/* eslint-disable */
/**
 * Author
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse5001
 */
export interface InlineResponse5001 {
    /**
     * Error message
     * @type {string}
     * @memberof InlineResponse5001
     */
    error: string;
}

export function InlineResponse5001FromJSON(json: any): InlineResponse5001 {
    return InlineResponse5001FromJSONTyped(json, false);
}

export function InlineResponse5001FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse5001 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': json['error'],
    };
}

export function InlineResponse5001ToJSON(value?: InlineResponse5001 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': value.error,
    };
}


