/* tslint:disable */
/* eslint-disable */
/**
 * Author
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineObject2
 */
export interface InlineObject2 {
    /**
     * 
     * @type {string}
     * @memberof InlineObject2
     */
    actor: string;
    /**
     * 
     * @type {string}
     * @memberof InlineObject2
     */
    action: InlineObject2ActionEnum;
    /**
     * 
     * @type {string}
     * @memberof InlineObject2
     */
    resource: string;
}

export function InlineObject2FromJSON(json: any): InlineObject2 {
    return InlineObject2FromJSONTyped(json, false);
}

export function InlineObject2FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject2 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'actor': json['actor'],
        'action': json['action'],
        'resource': json['resource'],
    };
}

export function InlineObject2ToJSON(value?: InlineObject2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'actor': value.actor,
        'action': value.action,
        'resource': value.resource,
    };
}

/**
* @export
* @enum {string}
*/
export enum InlineObject2ActionEnum {
    Read = 'read',
    Delete = 'delete',
    Edit = 'edit'
}


